name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Replace with the name of your master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command if different

      - name: Deploy to GitHub Pages
        uses: chanakya6/gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # This should match the build output directory
